{% set name = "vipaccess" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dlenski/python-{{ name }}/archive/v{{ version }}.tar.gz
  sha256: ceee345ea955603ed31f6c34e44aff08e7447ece08c60ee40d520bac4fc0d705

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - vipaccess = vipaccess.cli:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - lxml ==4.2.5
    - oath >=1.4.1
    - pycryptodome ==3.6.6
    - requests

test:
  imports:
    - vipaccess
    - vipaccess.cli
  commands:
    - vipaccess --help

about:
  home: https://github.com/dlenski/python-vipaccess
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: A free software implementation of Symantec's VIP Access application and protocol
  description: |
      If you need to access a network which uses VIP Access for two-factor
      authentication, but can't or don't want to use Symantec's proprietary
      applications—which are only available for Windows, MacOS, Android, iOS —
      then this is for you.
  doc_url: https://github.com/dlenski/python-vipaccess
  dev_url: https://github.com/dlenski/python-vipaccess

extra:
  recipe-maintainers:
    - kynan
