{% set name = "vipaccess" %}
{% set version = "0.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dlenski/python-{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 4a389f382eecd21763ef3c53c1e5fdb677ca4160a5da2f2cdbc63c5f7c201f76

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - vipaccess = vipaccess.__main__:main

requirements:
  host:
    - python >=3.3
    - pip
  run:
    - python >=3.3
    - lxml ==4.2.5
    - oath >=1.4.1
    - pycryptodome ==3.6.6
    - requests

test:
  imports:
    - vipaccess
  commands:
    - vipaccess --help

about:
  home: https://github.com/dlenski/python-vipaccess
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: A free software implementation of Symantec's VIP Access application and protocol
  description: |
    If you need to access a network which uses VIP Access for two-factor
    authentication, but can't or don't want to use Symantec's proprietary
    applications—which are only available for Windows, MacOS, Android, iOS —
    then this is for you.
  doc_url: https://github.com/dlenski/python-vipaccess
  dev_url: https://github.com/dlenski/python-vipaccess

extra:
  recipe-maintainers:
    - kynan
