travis:
  secure:
    BINSTAR_TOKEN: ml1skBTmwH1VnYhrr50UUApKonOFCtzRpofj6iug/3jnFjqasQF5kBDVgCUCVEcc0LFum1uqsFs0P7sT7gmGxW9kCPXeLaSc+MXnIi5emTBo3EIFm7TEpsoq2OS0Z9WZQDv7iNMuu9hqK7iwdr8qBJBiaffan5KvlNP/7ImFXZ5+2sDtINlNH+ifcz4AdZG3aK4q6Cn8lBcSK3JRnrMLZ47260QD2YfhU/+T1D7BggQRKNpuckZMIt/jnDkMp0Kg57z3GGZNn4AU9a4ee+ck6YMi9cwEE31zW6Q27+/eIbtNpR0/DAO0s4VEAPvw/oPteG/wysSzw9Gwl863WJVTzRomPNNWdrln9FJvvgQCdjKtN6dWbQqFUM3sHbd3yCXGxUwsH73yyMpyjSTyoIThI6WCygfcIa+lAQv42umjHqA+mXDAULIYFHWN2r64wAQSMvd3AHwTWBV6EsSpWlOIYZoJcXI6j0KjYRub1fZ2Wcl2DypfLJGFNsv46H2lwiyk1nnyqV6EAew2tKDblTlWLtfbOEbgeiKYJMEuUehGdx2Fi11fX/ZbHNgKLFrMOFobfjlHey0BCN/IaBfi1GDC0KSYj4V5xP9T+MwCa5n/pG1smj7agMhZatSdm2FR3iLdjaU0GoC6b+c38zdAbyh66WrcimxUJ3GO0K0KDx7DQ2A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
